### ISSUE TITLE
64 bit integers on non 64 bit architectures

### ISSUE THREAD

**Issue by rohan-panchal** [supermarin/ObjectiveRecord#116]
setSafeValue:forKey in NSManagedObject(ActiveRecord) checks for NSInteger16AttributeType || NSInteger32AttributeType || NSInteger64AttributeType but then it sets the NSNumber value with numberWithIntegerValue:.

On non 64 bit architectures this truncates the values if they are larger.
http://stackoverflow.com/questions/3707029/nsstring-to-64-bit-integer-conversion-on-iphone

**Comment by stephencelis** [comment]
Good catch and thanks for the PR!

**Comment by stephencelis** [comment]
Closed by #117.
