### ISSUE TITLE
How should I delete a cascade entity?

### ISSUE THREAD

**Issue by popularizan** [supermarin/ObjectiveRecord#122]
How do I delete an entity that is related to another in cascade? Should I make a "delete" & "save" for N  times ? One for each entity ?
I only delete the cascaded entities when I run the app for the second time

**Comment by supermarin** [comment]
I'm pretty sure calling -save on a top one would do the job, since it's telling the managed object context to save it's stuff. Given all your objects are in the same context, this should work.
