### ISSUE TITLE
Dictionaries nested more than 1 level deep break findOrCreate:

### ISSUE THREAD

**Issue by kattrali** [supermarin/ObjectiveRecord#60]
Right now OR handles creating nested entity objects during `update:` using the classes specified in an entity's `mappings` block. However, when a dictionary contains multiple levels of objects, the nested dictionaries aren't processed recursively, and are treated like values for entity property keys, so `-[NSManagedObject predicateForDictionary:]` returns a format like: `id == 4 AND type == Cajun AND owner == { id = 6 }`, resulting in a crash, since the owner value is not in a valid format.
#### Example

**Given** I have a `Restaurant` class, an `Owner` class, and a `Car` class, where a `Restaurant` has an `Owner` and an `Owner` has a `Car`

``` objc
@implementation Restaurant
+ (NSDictionary *)mappings {
        return @{ @"id" : @"restaurantID",
                          @"owner" : @{ @"class" : [Owner class]}};
}
@end

@implementation Owner
+ (NSDictionary *)mappings {
        return @{ @"id" : @"ownerID",
                          @"car" : @{ @"class" : [Car class]}};
}
@end

@implementation Car
+ (NSDictionary *)mappings {
        return @{ @"id" : @"carID" };
}
@end
```

**When** I want to update my `Restaurant` instance with a dictionary that looks like so:

``` objc
[restaurant update:@{
        @"id" : @4, 
        @"type" : @"Cajun",
        @"owner" : @{ 
                @"id" : @6, 
                @"full_name" : @"Rory Hill"
                @"car" : @{ @"id" : @43, @"model" : @"3"}}}];
```

**Then** I should have one `Restaurant`, one `Owner`, and one `Car` when the update is complete.

**Comment by donly** [comment]
I still have the `'to-many key not allowed here'` error there

``` Objective-C
// Car+Mappings.m
@implementation Car (Mappings)

+ (NSDictionary *)mappings {
    return @{
             @"seats": @{@"class": [Seat class]},
             @"owner": @{@"class": [Person class]
        },
    };
}

@end

// Seat+Mappings.m
@implementation Seat (Mappings)

+ (NSDictionary *)mappings {
    return @{
             @"car": @{@"class": [Car class]},
             };
}

@end

// using the below JSON data
NSDictionary *JSON = @{
                           @"first_name": @"Marin",
                           @"last_name": @"Usalj",
                           @"age": @25,
                           @"is_member": @"true",
                           @"cars": @[
                                   @{ @"hp": @220, @"make": @"Trabant",
                                      @"seats": @[
                                              @{@"orderId": @1},
                                              @{@"orderId": @2},
                                              ]},
                                   ],
                           };

    Person *person = [Person create:JSON];
```

Am I something wrong here

**Comment by Alexandeer** [comment]
For those who are faced with this problem. Find a different framework. This crude.

**Comment by Alexandeer** [comment]
> - (id)objectOrSetOfObjectsFromValue:(id)value ofClass:class inContext:(NSManagedObjectContext *)context {
>   if ([value isKindOfClass:class])
>       return value;
>   
>   if ([value isKindOfClass:[NSDictionary class]])
>       return [class findOrCreate:value inContext:context];
>   
>   if ([value isKindOfClass:[NSArray class]] || [value isKindOfClass:[NSSet class]])
>       return [NSSet setWithArray:[value map:^id(id object) {
>           return [self objectOrSetOfObjectsFromValue:object ofClass:class inContext:context];
>       }]];
>   
>   if ([class class] == [NSDate class])
>       return [NSDate dateWithTimeIntervalSince1970:[value floatValue]];
>   
>   return [class findOrCreate:@{ [class primaryKey]: value } inContext:context];
>   }

This code helped me.
